package com.model;

import java.util.Date;



/**
 * TChushou generated by MyEclipse Persistence Tools
 */

public class TChushou implements java.io.Serializable
{

	private Integer id;
	private TUser tuser;

	private String huxing;
	private Integer mianji;
	private String zhuangxiu;

	private Integer jiage;
	private String dizhi;
	private String lianxiren;
	private String lianxihua;

	private String fujian;
	private Date fabushi;
	private String zt;

	

	public TChushou(){

	}


	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}





	public String getHuxing()
	{
		return huxing;
	}
	public void setHuxing(String huxing)
	{
		this.huxing = huxing;
	}
	public Integer getMianji()
	{
		return mianji;
	}
	public void setMianji(Integer mianji)
	{
		this.mianji = mianji;
	}
	public String getZhuangxiu()
	{
		return zhuangxiu;
	}
	public void setZhuangxiu(String zhuangxiu)
	{
		this.zhuangxiu = zhuangxiu;
	}
	public Integer getJiage()
	{
		return jiage;
	}


	public void setJiage(Integer jiage)
	{
		this.jiage = jiage;
	}
	public String getDizhi()
	{
		return dizhi;
	}
	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;

	}
	public String getLianxiren()
	{
		return lianxiren;
	}
	public void setLianxiren(String lianxiren)
	{
		this.lianxiren = lianxiren;
	}

	public String getLianxihua()
	{
		return lianxihua;
	}
	public void setLianxihua(String lianxihua)
	{
		this.lianxihua = lianxihua;
	}

	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	


	


	public Date getFabushi() {
		return fabushi;
	}


	public void setFabushi(Date fabushi) {
		this.fabushi = fabushi;
	}


	public String getZt()
	{
		return zt;
	}
	public void setZt(String zt)
	{
		this.zt = zt;
	}




	

	public TUser getTuser() {
		return tuser;
	}


	public void setTuser(TUser tuser) {
		this.tuser = tuser;
	}



}