package com.model;

import java.util.Date;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable {

	private Integer liuyanId;
	private TUser tuser;
	
	private String liuyanTitle;
	private String liuyanContent;
	private Date liuyanDate;

	private String huifuContent;
	private Date huifuDate;

	public TUser getTuser() {
		return tuser;
	}

	public void setTuser(TUser tuser) {
		this.tuser = tuser;
	}

	public Integer getLiuyanId() {
		return liuyanId;
	}

	public void setLiuyanId(Integer liuyanId) {
		this.liuyanId = liuyanId;
	}

	public String getLiuyanTitle() {
		return liuyanTitle;
	}

	public void setLiuyanTitle(String liuyanTitle) {
		this.liuyanTitle = liuyanTitle;
	}

	public String getLiuyanContent() {
		return liuyanContent;
	}

	public void setLiuyanContent(String liuyanContent) {
		this.liuyanContent = liuyanContent;
	}

	

	public String getHuifuContent() {
		return huifuContent;
	}

	public void setHuifuContent(String huifuContent) {
		this.huifuContent = huifuContent;
	}

	public Date getLiuyanDate() {
		return liuyanDate;
	}

	public void setLiuyanDate(Date liuyanDate) {
		this.liuyanDate = liuyanDate;
	}

	public Date getHuifuDate() {
		return huifuDate;
	}

	public void setHuifuDate(Date huifuDate) {
		this.huifuDate = huifuDate;
	}

	
}