package com.model;

import java.util.Date;

/**
 * TQiugou generated by MyEclipse Persistence Tools
 */

public class TQiuzu implements java.io.Serializable
{

	private Integer id;
	private TUser tuser;
	
	
	private String huxing;
	private Integer mianji;
	private String zhuangxiu;

	private Integer jiage;
	private String dizhi;
	private String lianxiren;
	private String lianxihua;

	private Date fabushi;
	private String zt;
	

	// Constructors

	/** default constructor */
	public TQiuzu()
	{
	}

	

	

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	
	

	
	
	public TUser getTuser() {
		return tuser;
	}

	public void setTuser(TUser tuser) {
		this.tuser = tuser;
	}

	public String getHuxing()
	{
		return this.huxing;
	}

	public void setHuxing(String huxing)
	{
		this.huxing = huxing;
	}

	public Integer getMianji()
	{
		return this.mianji;
	}

	public void setMianji(Integer mianji)
	{
		this.mianji = mianji;
	}

	public String getZhuangxiu()
	{
		return this.zhuangxiu;
	}

	public void setZhuangxiu(String zhuangxiu)
	{
		this.zhuangxiu = zhuangxiu;
	}

	public Integer getJiage()
	{
		return this.jiage;
	}

	public void setJiage(Integer jiage)
	{
		this.jiage = jiage;
	}

	public String getDizhi()
	{
		return this.dizhi;
	}

	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;
	}

	public String getLianxiren()
	{
		return this.lianxiren;
	}

	public void setLianxiren(String lianxiren)
	{
		this.lianxiren = lianxiren;
	}

	public String getLianxihua()
	{
		return this.lianxihua;
	}

	public void setLianxihua(String lianxihua)
	{
		this.lianxihua = lianxihua;
	}

	public Date getFabushi()
	{
		return this.fabushi;
	}

	public void setFabushi(Date fabushi)
	{
		this.fabushi = fabushi;
	}

	public String getZt()
	{
		return this.zt;
	}

	public void setZt(String zt)
	{
		this.zt = zt;
	}

	
	

}