package com.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPw;

	private String userRealname;
	private String userSex;
	private String userAge;

	private String userAddress;
	private String userTel;
	private String userDel;

	private Set<TChushou> chushous = new HashSet<TChushou>();
	private Set<TChuzu> chuzus = new HashSet<TChuzu>();
	private Set<TLiuyan> liuyans = new HashSet<TLiuyan>();
	
	private Set<TQiugou> qiugous = new HashSet<TQiugou>();
	private Set<TQiuzu> qiuzus = new HashSet<TQiuzu>();

	public Set<TLiuyan> getLiuyans() {
		return liuyans;
	}

	public void setLiuyans(Set<TLiuyan> liuyans) {
		this.liuyans = liuyans;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserAge() {
		return userAge;
	}

	public void setUserAge(String userAge) {
		this.userAge = userAge;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public String getUserRealname() {
		return userRealname;
	}

	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	public String getUserSex() {
		return userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserTel() {
		return userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public String getUserDel() {
		return userDel;
	}

	public void setUserDel(String userDel) {
		this.userDel = userDel;
	}

	

	public Set<TChuzu> getChuzus() {
		return chuzus;
	}

	public void setChuzus(Set<TChuzu> chuzus) {
		this.chuzus = chuzus;
	}

	public Set<TChushou> getChushous() {
		return chushous;
	}

	public void setChushous(Set<TChushou> chushous) {
		this.chushous = chushous;
	}

	public Set<TQiugou> getQiugous() {
		return qiugous;
	}

	public void setQiugous(Set<TQiugou> qiugous) {
		this.qiugous = qiugous;
	}

	public Set<TQiuzu> getQiuzus() {
		return qiuzus;
	}

	public void setQiuzus(Set<TQiuzu> qiuzus) {
		this.qiuzus = qiuzus;
	}

}